# Generated by Django 3.0.4 on 2021-01-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=50)),
                ('collegeAddress', models.CharField(max_length=50)),
                ('collegeState', models.CharField(max_length=50)),
                ('collegeCity', models.CharField(max_length=20)),
                ('collegePhoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
