# Generated by Django 3.1.7 on 2021-03-31 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('COS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
