# Generated by Django 3.1.7 on 2021-04-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(max_length=50)),
                ('collegeAddress', models.CharField(max_length=50)),
                ('collegeState', models.CharField(max_length=50)),
                ('collegeCity', models.CharField(max_length=20)),
                ('collegePhoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'SOS_COLLEGE',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.CharField(max_length=100)),
                ('courseDuration', models.CharField(max_length=100)),
                ('collegeName', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='COS_API.college')),
            ],
            options={
                'db_table': 'SOS_COURSE',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectDescription', models.CharField(max_length=50)),
                ('college_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COS_API.college')),
                ('course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COS_API.course')),
            ],
            options={
                'db_table': 'SOS_SUBJECT',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=20)),
                ('mobile_Number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('college_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='COS_API.college')),
            ],
            options={
                'db_table': 'SOS_STUDENT',
            },
        ),
    ]
